//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobPortalModel {
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    
    
    public class CompanyDetails {
        
        private Int32 _Id;
        
        private String _CompanyName;
        
        private String _WebsiteURL;
        
        private Int32 _IndustryID;
        
        private String _Description;
        
        private String _Status;
        
        public CompanyDetails(int ID) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand("select * from CompanyDetails where ID = " + ID , ObjConnection);
			SqlDataReader ObjReader = ObjCommand.ExecuteReader();
			ObjReader.Read();
			if(ObjReader["Id"] != DBNull.Value)
				Id = (int)ObjReader["Id"];
			if(ObjReader["CompanyName"] != DBNull.Value)
				CompanyName = (string)ObjReader["CompanyName"];
			if(ObjReader["WebsiteURL"] != DBNull.Value)
				WebsiteURL = (string)ObjReader["WebsiteURL"];
			if(ObjReader["IndustryID"] != DBNull.Value)
				IndustryID = (int)ObjReader["IndustryID"];
			if(ObjReader["Description"] != DBNull.Value)
				Description = (string)ObjReader["Description"];
			if(ObjReader["Status"] != DBNull.Value)
				Status = (string)ObjReader["Status"];
			ObjReader.Close();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
        }
        
        public virtual Int32 Id {
            get {
				return _Id;
            }
            set {
				_Id = value;
            }
        }
        
        public virtual String CompanyName {
            get {
				return _CompanyName;
            }
            set {
				_CompanyName = value;
            }
        }
        
        public virtual String WebsiteURL {
            get {
				return _WebsiteURL;
            }
            set {
				_WebsiteURL = value;
            }
        }
        
        public virtual Int32 IndustryID {
            get {
				return _IndustryID;
            }
            set {
				_IndustryID = value;
            }
        }
        
        public virtual String Description {
            get {
				return _Description;
            }
            set {
				_Description = value;
            }
        }
        
        public virtual String Status {
            get {
				return _Status;
            }
            set {
				_Status = value;
            }
        }
        
        public static Int32 AddCompanyDetails(String CompanyName, String WebsiteURL, Int32 IndustryID, String Description, String Status) {
			string strsql = "insert into CompanyDetails output inserted.id values(" + "'"+ CompanyName.Replace("'","''") + "'," + "'"+ WebsiteURL.Replace("'","''") + "'," + IndustryID + "," + "'"+ Description.Replace("'","''") + "'," + "'"+ Status.Replace("'","''") + "'" + ")"; 
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			int NewID = (int) ObjCommand.ExecuteScalar();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
			return NewID;
        }
        
        public static DataTable GetCompanyDetailsRecords(string WhereClause) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			DataTable ObjDataTable= new DataTable();
			string strsql ="select * from CompanyDetails";
			if(WhereClause != String.Empty) strsql= strsql + " where " + WhereClause;
			SqlDataAdapter ObjAdapter = new SqlDataAdapter(strsql,ObjConnection);
			ObjAdapter.Fill(ObjDataTable);
			ObjAdapter.Dispose();
			ObjConnection.Dispose();
			return ObjDataTable;
        }
        
        public void Update() {
			string strsql= "update CompanyDetails set " + "CompanyName= '" + CompanyName.Replace("'","''") + "', " + "WebsiteURL= '" + WebsiteURL.Replace("'","''") + "', " + "IndustryID= " + IndustryID + ", " + "Description= '" + Description.Replace("'","''") + "', " + "Status= '" + Status.Replace("'","''") + "' " + " where ID ="  + Id ;
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			ObjCommand.ExecuteNonQuery();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
        }
        
        public static void DeleteCompanyDetailsRecords(string WhereClause) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			DataTable ObjDataTable= new DataTable();
			string strsql ="delete from CompanyDetails";
			if(WhereClause != String.Empty) strsql= strsql + " where " + WhereClause;
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			ObjCommand.ExecuteNonQuery();
			ObjCommand.Dispose();
			ObjConnection.Dispose();
        }
    }
}
