//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyJobPortalModel {
    using System;
    using System.Data;
    using System.Data.SqlClient;
    using System.Configuration;
    
    
    public class Person {
        
        private Int32 _Id;
        
        private Int32 _TitleId;
        
        private String _FirstName;
        
        private String _LastName;
        
        private String _EmailId;
        
        private String _Password;
        
        private String _Role;
        
        private String _Status;
        
        private Boolean _EnableEmail;
        
        public Person(int ID) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand("select * from Person where ID = " + ID , ObjConnection);
			SqlDataReader ObjReader = ObjCommand.ExecuteReader();
			ObjReader.Read();
			if(ObjReader["Id"] != DBNull.Value)
				Id = (int)ObjReader["Id"];
			if(ObjReader["TitleId"] != DBNull.Value)
				TitleId = (int)ObjReader["TitleId"];
			if(ObjReader["FirstName"] != DBNull.Value)
				FirstName = (string)ObjReader["FirstName"];
			if(ObjReader["LastName"] != DBNull.Value)
				LastName = (string)ObjReader["LastName"];
			if(ObjReader["EmailId"] != DBNull.Value)
				EmailId = (string)ObjReader["EmailId"];
			if(ObjReader["Password"] != DBNull.Value)
				Password = (string)ObjReader["Password"];
			if(ObjReader["Role"] != DBNull.Value)
				Role = (string)ObjReader["Role"];
			if(ObjReader["Status"] != DBNull.Value)
				Status = (string)ObjReader["Status"];
			if(ObjReader["EnableEmail"] != DBNull.Value)
				EnableEmail = (bool)ObjReader["EnableEmail"];
			ObjReader.Close();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
        }
        
        public virtual Int32 Id {
            get {
				return _Id;
            }
            set {
				_Id = value;
            }
        }
        
        public virtual Int32 TitleId {
            get {
				return _TitleId;
            }
            set {
				_TitleId = value;
            }
        }
        
        public virtual String FirstName {
            get {
				return _FirstName;
            }
            set {
				_FirstName = value;
            }
        }
        
        public virtual String LastName {
            get {
				return _LastName;
            }
            set {
				_LastName = value;
            }
        }
        
        public virtual String EmailId {
            get {
				return _EmailId;
            }
            set {
				_EmailId = value;
            }
        }
        
        public virtual String Password {
            get {
				return _Password;
            }
            set {
				_Password = value;
            }
        }
        
        public virtual String Role {
            get {
				return _Role;
            }
            set {
				_Role = value;
            }
        }
        
        public virtual String Status {
            get {
				return _Status;
            }
            set {
				_Status = value;
            }
        }
        
        public virtual Boolean EnableEmail {
            get {
				return _EnableEmail;
            }
            set {
				_EnableEmail = value;
            }
        }
        
        public static Int32 AddPerson(Int32 TitleId, String FirstName, String LastName, String EmailId, String Password, String Role, String Status, Boolean EnableEmail) {
			string strsql = "insert into Person output inserted.id values(" + TitleId + "," + "'"+ FirstName.Replace("'","''") + "'," + "'"+ LastName.Replace("'","''") + "'," + "'"+ EmailId.Replace("'","''") + "'," + "'"+ Password.Replace("'","''") + "'," + "'"+ Role.Replace("'","''") + "'," + "'"+ Status.Replace("'","''") + "'," + Convert.ToInt32(EnableEmail) + ")"; 
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			int NewID = (int) ObjCommand.ExecuteScalar();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
			return NewID;
        }
        
        public static DataTable GetPersonRecords(string WhereClause) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			DataTable ObjDataTable= new DataTable();
			string strsql ="select * from Person";
			if(WhereClause != String.Empty) strsql= strsql + " where " + WhereClause;
			SqlDataAdapter ObjAdapter = new SqlDataAdapter(strsql,ObjConnection);
			ObjAdapter.Fill(ObjDataTable);
			ObjAdapter.Dispose();
			ObjConnection.Dispose();
			return ObjDataTable;
        }
        
        public void Update() {
			string strsql= "update Person set " + "TitleId= " + TitleId + ", " + "FirstName= '" + FirstName.Replace("'","''") + "', " + "LastName= '" + LastName.Replace("'","''") + "', " + "EmailId= '" + EmailId.Replace("'","''") + "', " + "Password= '" + Password.Replace("'","''") + "', " + "Role= '" + Role.Replace("'","''") + "', " + "Status= '" + Status.Replace("'","''") + "', " + "EnableEmail= " + Convert.ToInt32(EnableEmail) + " " + " where ID ="  + Id ;
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			ObjCommand.ExecuteNonQuery();
			ObjConnection.Dispose();
			ObjCommand.Dispose();
        }
        
        public static void DeletePersonRecords(string WhereClause) {
			SqlConnection ObjConnection = new SqlConnection(ConfigurationManager.ConnectionStrings["MyJobPortal"].ConnectionString);
			ObjConnection.Open();
			DataTable ObjDataTable= new DataTable();
			string strsql ="delete from Person";
			if(WhereClause != String.Empty) strsql= strsql + " where " + WhereClause;
			SqlCommand ObjCommand = new SqlCommand(strsql,ObjConnection);
			ObjCommand.ExecuteNonQuery();
			ObjCommand.Dispose();
			ObjConnection.Dispose();
        }
    }
}
